// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtRN_r7sgNJIrGrL2op8wujOUB353DaM',
    appId: '1:808759168821:web:a334a4711f3cfa1349067c',
    messagingSenderId: '808759168821',
    projectId: 'studyapp-7ca98',
    authDomain: 'studyapp-7ca98.firebaseapp.com',
    storageBucket: 'studyapp-7ca98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5EzCHT9tkAzJ5AcJUw2Rc6JWYx8db0_Q',
    appId: '1:808759168821:android:a92d949e9707295849067c',
    messagingSenderId: '808759168821',
    projectId: 'studyapp-7ca98',
    storageBucket: 'studyapp-7ca98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMxcvkQKtSM7Fw9zGJ4sp8LDAdYrJMS4',
    appId: '1:808759168821:ios:57ef9a0919063b3049067c',
    messagingSenderId: '808759168821',
    projectId: 'studyapp-7ca98',
    storageBucket: 'studyapp-7ca98.firebasestorage.app',
    iosBundleId: 'com.example.studyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKMxcvkQKtSM7Fw9zGJ4sp8LDAdYrJMS4',
    appId: '1:808759168821:ios:57ef9a0919063b3049067c',
    messagingSenderId: '808759168821',
    projectId: 'studyapp-7ca98',
    storageBucket: 'studyapp-7ca98.firebasestorage.app',
    iosBundleId: 'com.example.studyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMtRN_r7sgNJIrGrL2op8wujOUB353DaM',
    appId: '1:808759168821:web:02634fc1197520d049067c',
    messagingSenderId: '808759168821',
    projectId: 'studyapp-7ca98',
    authDomain: 'studyapp-7ca98.firebaseapp.com',
    storageBucket: 'studyapp-7ca98.firebasestorage.app',
  );
}
